import js from '@eslint/js';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      '**/dist/**',
      '**/node_modules/**',
      '**/.output/**',
      '**/.wxt/**',
      '**/pkg/**',
      'target/**',
      'chrome/**',
      // Generated by wasm-pack; not ours to edit.
      'packages/extension/wasm/**',
      'packages/extension/public/**',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    rules: {
      // Keep secrets from accidentally reaching the log (AGENTS.md security rules).
      'no-console': ['error', { allow: ['warn', 'error'] }],
      '@typescript-eslint/no-explicit-any': 'error',
    },
  },
  {
    // Development-only Node scripts, where console output is the deliverable.
    files: ['**/scripts/**/*.mjs', '*.config.{js,ts,mjs}'],
    languageOptions: {
      globals: {
        console: 'readonly',
        process: 'readonly',
        URL: 'readonly',
        // Code inside page.evaluate runs in the browser context.
        chrome: 'readonly',
        performance: 'readonly',
      },
    },
    rules: { 'no-console': 'off' },
  },
);
